"""Added target ide and supervisor to PushMessage

Revision ID: 02801ab9de76
Revises: 066d39a27178
Create Date: 2026-02-26 00:05:06.563014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02801ab9de76'
down_revision = '066d39a27178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_ide_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_supervisor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'membros', ['target_supervisor_id'], ['id'])
        batch_op.create_foreign_key(None, 'ides', ['target_ide_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('target_supervisor_id')
        batch_op.drop_column('target_ide_id')

    # ### end Alembic commands ###
