"""Add pastor_id to Ide

Revision ID: 0bb2d7a81c92
Revises: 690302c57f53
Create Date: 2026-02-01 13:46:04.748116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb2d7a81c92'
down_revision = '690302c57f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pastor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ides_pastor_id_membros', 'membros', ['pastor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ides', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ides_pastor_id_membros', type_='foreignkey')
        batch_op.drop_column('pastor_id')

    # ### end Alembic commands ###
