"""add requer_troca_senha to user

Revision ID: 0dd1cffb716f
Revises: 37571d4d8945
Create Date: 2026-02-15 16:12:45.498010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd1cffb716f'
down_revision = '37571d4d8945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requer_troca_senha', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('requer_troca_senha')

    # ### end Alembic commands ###
