"""Add is_batismo to Evento

Revision ID: 124a143e6a5b
Revises: b2c3d4e5f6a7
Create Date: 2026-03-08 16:38:49.239216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '124a143e6a5b'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_batismo', sa.Boolean(), nullable=True))
    
    # Preenche eventos antigos com False
    op.execute("UPDATE eventos SET is_batismo = False")
    
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('is_batismo', nullable=False, server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('is_batismo')
    # ### end Alembic commands ###
