"""Add Evento model

Revision ID: 21dd7fa93b6e
Revises: 0571a0697825
Create Date: 2026-02-01 13:13:32.214523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dd7fa93b6e'
down_revision = '0571a0697825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
