"""add custom_css to projeto

Revision ID: 3551a0bed25c
Revises: a94263724a06
Create Date: 2026-03-08 20:35:07.525663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3551a0bed25c'
down_revision = 'a94263724a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_css', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_column('custom_css')

    # ### end Alembic commands ###
