"""Update celula model with naming convention v4

Revision ID: 37571d4d8945
Revises: 0bb2d7a81c92
Create Date: 2026-02-01 16:20:13.563351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37571d4d8945'
down_revision = '0bb2d7a81c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ide_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vice_lider_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('horario_reuniao', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'membros', ['lider_id'], ['id'])
        batch_op.create_foreign_key(None, 'membros', ['supervisor_id'], ['id'])
        batch_op.create_foreign_key(None, 'ides', ['ide_id'], ['id'])
        batch_op.create_foreign_key(None, 'membros', ['vice_lider_id'], ['id'])
        batch_op.drop_column('horario')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('horario', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['lider_id'], ['id'])
        batch_op.drop_column('logradouro')
        batch_op.drop_column('horario_reuniao')
        batch_op.drop_column('vice_lider_id')
        batch_op.drop_column('supervisor_id')
        batch_op.drop_column('ide_id')

    # ### end Alembic commands ###
