"""Add Celula model fixed

Revision ID: 690302c57f53
Revises: 21dd7fa93b6e
Create Date: 2026-02-01 13:38:06.562590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690302c57f53'
down_revision = '21dd7fa93b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=True),
    sa.Column('dia_reuniao', sa.String(length=20), nullable=True),
    sa.Column('horario', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['lider_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celulas')
    # ### end Alembic commands ###
