"""Add Projeto model and fix image fields

Revision ID: a94263724a06
Revises: 124a143e6a5b
Create Date: 2026-03-08 20:16:33.748184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a94263724a06'
down_revision = '124a143e6a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('subtitulo', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('descricao_home', sa.Text(), nullable=True),
    sa.Column('imagem_capa', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('paginas', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('celulas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_celulas_ativo'))
        batch_op.drop_index(batch_op.f('ix_celulas_ide_id'))
        batch_op.drop_index(batch_op.f('ix_celulas_lider_id'))
        batch_op.drop_index(batch_op.f('ix_celulas_supervisor_id'))

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('is_batismo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('perguntas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.create_foreign_key(None, 'ides', ['ide_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['criado_por_id'], ['id'])

    with op.batch_alter_table('inscricoes_eventos', schema=None) as batch_op:
        batch_op.alter_column('respostas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membros_ativo'))
        batch_op.drop_index(batch_op.f('ix_membros_ativo_ide'))
        batch_op.drop_index(batch_op.f('ix_membros_ide_id'))
        batch_op.drop_index(batch_op.f('ix_membros_lider_id'))
        batch_op.drop_index(batch_op.f('ix_membros_supervisor_id'))

    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.alter_column('foto_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('papeis_membros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papeis_membros_membro_id'))
        batch_op.drop_index(batch_op.f('ix_papeis_membros_papel'))
        batch_op.drop_index(batch_op.f('ix_papeis_membros_role_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papeis_membros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papeis_membros_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papeis_membros_papel'), ['papel'], unique=False)
        batch_op.create_index(batch_op.f('ix_papeis_membros_membro_id'), ['membro_id'], unique=False)

    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.alter_column('foto_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membros_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membros_lider_id'), ['lider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membros_ide_id'), ['ide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membros_ativo_ide'), ['ativo', 'ide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membros_ativo'), ['ativo'], unique=False)

    with op.batch_alter_table('inscricoes_eventos', schema=None) as batch_op:
        batch_op.alter_column('respostas',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('perguntas',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('is_batismo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('celulas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_celulas_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_celulas_lider_id'), ['lider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_celulas_ide_id'), ['ide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_celulas_ativo'), ['ativo'], unique=False)

    op.drop_table('projetos')
    # ### end Alembic commands ###
